import struct
import binascii
from impacket.structure import Structure


class ServerResponseParser(Structure):
    commonHdr = (
        ('TPKTVersion', 'B=3'),
        ('TPKTReserved', 'B=0'),
        ('TPKTLength', '>H=len(TPDU)+4'),
        ('_TPDU', '_-TPDU', 'self["TPKTLength"]-4'),
        ('x224length', 'B=0'),
        ('x224pduType', 'B=0'),
        ('x224Number', 'B=0'),
        ('idk1', 'H'),
        ('connect-response', 'B'),
        ('idk2', 'H'),
        ('rt-successful', 'B'),
        ('idk3', 'H'),
        ('calledConnectId', 'B'),
        ('idk4', 'H'),
        ('idk5', 'H'),
        ('maxChannelIds', 'B'),
        ('idk6', 'H'),
        ('maxUserIds', 'B'),
        ('idk7', 'H'),
        ('maxTokenIds', 'B'),
        ('idk8', 'H'),
        ('numPriorities', 'B'),
        ('idk9', 'H'),
        ('minThoughtput', 'B'),
        ('idk10', 'H'),
        ('maxHeight', 'B'),
        ('idk11', 'H'),
        ('maxMcsPDUsize', 'H'),
        ('idk12', 'H'),
        ('idk13', 'B'),
        ('protocolVersion', 'B'),
        ('idk14', 'H'),
        ('idk15', 'H'),
        ('t124Identifier', '<L=5'),
        ('idk16', 'H'),
        ('NodeID', 'H'),
        ('tag', 'H'),
        ('result', 'B'),
        ('idk17', 'B'),
        ('h221NonStandard', '<L=%s'),
        ('idk18', 'H'),
        ('idk19', 'H'),
        ('serverCoreData', 'H'),
        ('headerLength', 'H'),
        ('versionMajor', 'H'),
        ('versionMinor', 'H'),
        ('ClientRequestProtocols', 'I'),
        ('serverNetworkData', 'H'),
        ('headerLength2', 'H'),
        ('MSCSChannelId1', 'H'),
        ('channelCount', 'H'),
        ('MSCSChannelId1', 'H'),
        ('MSCSChannelId2', 'H'),
        ('MSCSChannelId3', 'H'),
        ('MSCSChannelId4', 'H'),
        ('MSCSChannelId5', 'H'),
        ('pad', 'H'),
        ('serverSecurityData', 'H'),
        ('headerLength3', 'H'),
        ('encMethod', 'i'),
        ('enclvl', 'i'),
        ('rest', ':=""'),
    )


class RoadTrip(Structure):
    commonHdr = (
        ('CSSP', 'd'),
        ('version', 'B'),
        ('rest', ':=""'),
    )


class NtlmNegoParser(Structure):
    commonHdr = (
        ('CSSP', 'd'),
        ('version', 'B'),
        ('idk1', 'd'),
        ('idk2', 'd'),
        ('ntlm', 'i'),
        ('ntlm', 'h'),
        ('ntlm', 'b'),
        ('ntlmtype', 'i'),
        ('lengthNTLM', 'h'),
        ('maxlength', 'h'),
        ('offest', 'i'),
        ('flags1', 'B'),
        ('flags2', 'B'),
        ('flags3', 'B'),
        ('flags4', 'B'),
        ('ntlmserverchallange', 'i'),
        ('ntlmserverchallange2', 'i'),
        ('reserved', 'd'),
        ('targetLen', 'H'),
        ('targetMaxLen', 'H'),
        ('targetoffest', 'i'),
        ('MajorVersion', 'B'),
        ('MinorVersion', 'B'),
        ('build', 'H'),
        ('pad', 'H'),
        ('pad', 'B'),
        ('revision', 'B'),
        ('rest', ':=""'),
    )

class NtlmNegoParser2(Structure):
    commonHdr = (
        ('MajorVersion', 'B'),
        ('MinorVersion', 'B'),
        ('build', 'H'),
        ('pad', 'H'),
        ('pad', 'B'),
        ('revision', 'B'),
        ('rest', ':=""'),
    )