import struct
import binascii
from impacket.structure import Structure


class ServerResponseParser(Structure):
    commonHdr = (
        ('TPKTVersion', 'B=3'),
        ('TPKTReserved', 'B=0'),
        ('TPKTLength', '>H=len(TPDU)+4'),
        ('_TPDU', '_-TPDU', 'self["TPKTLength"]-4'),
        ('x224length', 'B=0'),
        ('x224pduType', 'B=0'),
        ('x224Number', 'B=0'),
        ('idk1', 'H'),
        ('connect-response', 'B'),
        ('idk2', 'H'),
        ('rt-successful', 'B'),
        ('idk3', 'H'),
        ('calledConnectId', 'B'),
        ('idk4', 'H'),
        ('idk5', 'H'),
        ('maxChannelIds', 'B'),
        ('idk6', 'H'),
        ('maxUserIds', 'B'),
        ('idk7', 'H'),
        ('maxTokenIds', 'B'),
        ('idk8', 'H'),
        ('numPriorities', 'B'),
        ('idk9', 'H'),
        ('minThoughtput', 'B'),
        ('idk10', 'H'),
        ('maxHeight', 'B'),
        ('idk11', 'H'),
        ('maxMcsPDUsize', 'H'),
        ('idk12', 'H'),
        ('idk13', 'B'),
        ('protocolVersion', 'B'),
        ('idk14', 'H'),
        ('idk15', 'H'),
        ('t124Identifier', '<L=5'),
        ('idk16', 'H'),
        ('NodeID', 'H'),
        ('tag', 'H'),
        ('result', 'B'),
        ('idk17', 'B'),
        ('h221NonStandard', '<L=%s'),
        ('idk18', 'H'),
        ('idk19', 'H'),
        ('serverCoreData', 'H'),
        ('headerLength', 'H'),
        ('versionMajor', 'H'),
        ('versionMinor', 'H'),
        ('ClientRequestProtocols', 'I'),
        ('serverNetworkData', ':=""'),
    )